# -*- coding: utf-8 -*-
"""HW5 Q5 Kati Johnson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tK3LVJmUBe0LwysKsRBspzQI_KVBa9V-
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from google.colab import drive
drive.mount('/content/drive')

"""##Q5
Please follow the instructions below and inspect the outputs before you proceed. You can always check this original final to compare your results in your own copy.
"""

#You have to make sure that you were able to write the file to a csv while your were working in R
house=pd.read_csv('/content/drive/MyDrive/CSC302/DATA/house_prices.csv')
house.head()

"""a) For the states below, please select the rows from the house dataframe, and consider converting the date column to date data type as it may be coming in string format. Then use the head function to preview your new dataframe."""

states = ['Michigan', 'California', 'Texas', 'Indiana']
#your code goes here
statesdf = house.loc[(house['state'] == 'Michigan') | (house['state'] == 'California') | (house['state'] == 'Texas') | (house['state'] == 'Indiana')]

statesdf['date'] = pd.to_datetime(statesdf['date'])
statesdf.dtypes
statesdf.head()

"""b) Use the FacetGrid from seaborn to create line plots to represent house_price_index for each state. Please make the line color red, set ticks on x axis for years ['1980', '2000', '2020'], which you may have to convert date type again, put those years as labels, and set the titles for each small plot to their state names. In addition, set the y label to 'house price index' and remove the x label since it's obvious that these are years."""

#your code goes here
labels = ["1980", "2000", "2020"]
g = sns.FacetGrid(statesdf, col = "state")
g.map(sns.lineplot, 'date', 'house_price_index', color='red')
g.set(xticks=labels)
g.set_axis_labels("", "house price index" )

xformatter = mdates.DateFormatter("%Y")
g.axes[0,0].xaxis.set_major_formatter(xformatter)
titles = ['California', 'Indiana','Michigan', 'Texas']

for ax,title in zip(g.axes.flatten(),titles):
     ax.set_title(title)

"""c) Draw a lineplot for 'house price perc', but color them based on the 'state' name which will have four lines in a single plot. Set a legend which will be at the bottom of your graph and have them horizantally positioned next to eachother. Again, set the y label to house_price_perc and remove the x label since it's obvious. (Note that my y label is still showing index. Please ignore that.)"""

#your code goes here
fig, ax = plt.subplots()
sns.lineplot(data=statesdf, x='date', y='house_price_perc', hue='state')
plt.legend(loc='lower center', ncols=4)
ax.set_xlabel('')
ax.set_ylabel('house price perc')