---
title: "HW5"
author: "Kati Johnson"
date: "2023-04-09"
output: html_document
---
```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(ggplot2)
library(dplyr)
library(forcats)
library(ggmap)
library(statebins)
library(sf)
library(geofacet)
library(ggspatial)
library(colorspace)
library(cowplot)
library(lubridate)
```

#2A
``` {r filtering}
states <- map_data("state")
head(states)

california <- states[states$region=='california',]
head(california)
```

#2B
``` {r more filtering}
load("C:\\Users\\kati.johnson\\Desktop\\DATA\\wind_turbines.rda")
head(wind_turbines)
nrow(wind_turbines)

wind_ca <- wind_turbines[wind_turbines$t_state=='CA',]
head(wind_ca)
nrow(wind_ca)
```

#2C
``` {r plot1}
gg1 <- ggplot(data=california, aes(x=long, y=lat)) +
  geom_polygon(fill="navy")
gg1
```

#2D
``` {r plot2}
gg1 + geom_point(
  data = wind_ca,
  aes(x = xlong, y = ylat),
  size = 2,
  colour = "#FF5733",
  alpha = 1/3,
  position = 'jitter',
  show.legend = FALSE
) 

```
